apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: librechat
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/maximilianoPizarro/agnosticg.git'
    targetRevision: main
    path: charts/librechat-gitops/librechat
    helm:
      valueFiles:
        - helm-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: librechat
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
