apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: librechat

resources:
- ./helm-repository.yaml

helmCharts:
- name: mongodb
  repo: https://charts.bitnami.com/bitnami
  version: "16.3.0"
  releaseName: librechat-mongodb
- name: postgresql
  repo: https://charts.bitnami.com/bitnami
  version: "15.5.38"
  releaseName: librechat-postgresql
- name: librechat
  repo: https://maximilianopizarro.github.io/librechat/
  version: "1.8.10"
  releaseName: librechat-openshift
  #valuesFile: values.yaml
  #valuesInline:
  #  fullnameOverride: helloagain