apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: librechat

resources:
- ./helm-repository.yaml

helmCharts:
- name: librechat
  version: "1.8.10"
  releaseName: librechat
  repo: https://maximilianopizarro.github.io/librechat/
  valuesFile: values.yaml
  #valuesInline:
  #  fullnameOverride: helloagain