apiVersion: v2
name: developer-hub
description: A Helm chart to deploy Developer Hub resources for Kubernetes
type: application

version: 0.1.0
appVersion: 1.2.2

dependencies:
- name: developer-hub
  version: "1.2.2"
  repository: "https://charts.openshift.io/"