kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
  labels:
    {{- include "developer-hub.labels" . | nindent 4 }}
data:
  app-config-rhdh.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: https://rhdh-redhat-developer-hub-developer-hub.apps.cluster-pqp2q.pqp2q.sandbox1259.opentlc.com/
    auth:
      allowGuestAccess: true
      environment: development
    enabled:
      github: true
    kubernetes:
      customResources:
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'pipelineruns'
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'taskruns'  