apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhdh-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
  volumeMode: Filesystem