apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: rhdh-scc
allowPrivilegedContainer: false
allowedCapabilities: []
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowHostNamespace: false
allowPrivilegeEscalation: true
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
groups: []
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - ephemeral
  - persistentVolumeClaim
users:
  - system:serviceaccount:developer-hub:backstage-read-only